version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge
